// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import { Geist, Geist_Mono, Poppins, Playfair_Display, Dancing_Script } from "next/font/google";
import "./globals.css";

// Geist Sans and Geist Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Poppins font
const poppins = Poppins({
  weight: ["400", "600", "700"], // Specify the font weights you need
  subsets: ["latin"],
  variable: "--font-poppins", // Define a CSS variable for Poppins
});

// Playfair Display font (for "Ink")
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair", // Define a CSS variable for Playfair Display
});

// Dancing Script font (for "& Imagination")
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script", // Define a CSS variable for Dancing Script
});

export const metadata = {
  title: "Ink & Imagination",
  description: "Your one-stop shop for all kinds of books.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${playfair.variable} ${dancingScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}